config/routes.rb
PicShare::Application.routes.draw do
  get "welcome/index"
  get "events/show"

  post "photos/upload"

  resources :events
  resources :photos

  root 'welcome#index'

end

app/models/event.rb
class Event
  include Mongoid::Document
  has_many :medias

  field :name, type: String
  field :startDate, type: Date
  field :endDate, type: Date

  validates_presence_of :name, message: "Name is required"
  validates_presence_of :startDate, message: "Start Date is required"
  validates_presence_of :endDate, message: "End Date is required"
end

app/models/media.rb
class Media
  include Mongoid::Document
  include Magick
  include PicShareS3

  belongs_to :event

  field :md5
  field :caption
  field :adult_content, type: Mongoid::Boolean

  def media_file=(file)
    Uploader.new.async.perform file: file, photo_id: id
  end

  def media_url
    obj = bucket.objects[self._s3_filename]
    obj.url_for(:read)
  end

  def delete(options)
    bucket.objects[self._s3_filename].delete
    super
  end

  #protected

  field :_s3_filename, type: String
  field :_resized_s3_filename, type: String

end

app/models/photo.rb
class Photo < Media
  include Mongoid::Document

  def media_file=(file)
    super
    PhotoResizer.new.async.perform(photo_id: id, file: file, width: 240)
  end

  def media_url_240_wide
    if _resized_s3_filename.nil? || resized_bucket.objects[_resized_s3_filename].nil?
      PhotoResizer.new.perform(photo_id: id, width: 240)
    end
    resized_bucket.objects[self._resized_s3_filename].url_for(:read)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @media = @event.medias.where(:_s3_filename.exists => true, :_resized_s3_filename.exists => true)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :startDate, :endDate)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @event = Event.find(params[:event_id])
    @photo = Photo.new
    @photo.event_id = params[:event_id]
  end

  # GET /photos/1/edit
  def edit
    @events = Event.all
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo.event, notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  def upload
    @files = []
    params[:files].each do |file|
      Photo.create!({event_id: params[:event_id], media_file: file.tempfile })
      @files << { name: file.original_filename }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:caption, :adult_content, :media_url, :event_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @events = Event.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.haml
= form_for(@event, html: {class: 'form-horizontal'}) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        #{ pluralize(@event.errors.count, "error") } prohibited this event from being saved:
      %ul
        - @event.errors.each do |attribute,msg|
          %li #{ msg }

  .form-group.row
    = f.label :name, class: 'control-label'
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :startDate, "Start Date", class: 'control-label'
    = f.text_field :startDate, class: "datepicker form-control"

  .form-group
    = f.label :endDate, "End Date", class: 'control-label'
    = f.text_field :endDate, class: "datepicker form-control"

  .form-group.row
    = f.submit class: 'btn btn-primary'

app/views/events/_form.html.slim
= form_for(@event, html: {class: 'form-horizontal'}) do |f|
  - if @event.errors.any?
    #error_explanation
      h2 #{ pluralize(@event.errors.count, "error") } prohibited this event from being saved:
      ul
        - @event.errors.each do |attribute,msg|
          li #{ msg }

  .form-group.row
    = f.label :name, class: 'control-label'
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :startDate, "Start Date", class: 'control-label'
    = f.text_field :startDate, class: "datepicker form-control"

  .form-group
    = f.label :endDate, "End Date", class: 'control-label'
    = f.text_field :endDate, class: "datepicker form-control"

  .form-group.row
    = f.submit class: 'btn btn-primary'

app/views/events/edit.html.slim
.container
  h1 Editing event

  == render 'form'

  = link_to 'Show', @event
  = link_to 'Back', events_path

app/views/events/index.html.slim
.container
  h1 Listing events

  table
    thead
      tr
        th Name
        th
        th
        th

    tbody
      - @events.each do |event|
        tr
          td #{ event.name }
          td #{ link_to 'Show', event }
          td #{ link_to 'Edit', edit_event_path(event) }
          td #{ link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } }

  br

  = link_to 'New Event', new_event_path

app/views/events/new.html.haml
.container
  .jumbotron
    = render 'form'

app/views/events/new.html.slim
.container
  .jumbotron
    == render 'form'

app/views/events/show.html.slim
.container
  h1 #{ @event.name }

  == render partial: 'layouts/uploader'

  .gridalicious
    - @media.shuffle.each do |image|
      | <a href="#{image.media_url}" class="gridItem" data-colorbox=true data-colorbox-photo=true data-colorbox-max-width="98%" data-colorbox-max-height="98%">
      = image_tag image.media_url_240_wide, width: 240
      | </a>

app/views/layouts/_form.html.haml
%span.fileinput-button.btn.btn-primary.btn-sm
  %i.glyphicon.glyphicon-plus
  %span Select Files...
  %input#fileupload{type: "file", name: "files[]", 'data-url' => "/photos/upload", multiple: true, 'data-eventid' => "#{@event.id}"}
#progress
  .bar{style: "width:0%;"}

app/views/layouts/_navbar.html.slim
.navbar.navbar-default.navbar-fixed-top role = "navigation"
  .container
    .navbar-header
      button.navbar-toggle data-target = ".navbar-collapse" data-toggle = "collapse" type = "button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "PicShare", {controller: "welcome", action: 'index'}, class: "navbar-brand"

    .navbar-collapse.collapse
      ul.nav.navbar-nav
        li
          = link_to "Home", {controller: "welcome", action: 'index'}
        li
          a href = "#about" About
        li
      ul.nav.navbar-nav.navbar-right
        li.hidden
          = link_to "Login", {controller: "welcome", action: 'index'}

app/views/layouts/_uploader.html.slim
span.fileinput-button.btn.btn-primary.btn-sm
  span Upload Photos...
  input#fileupload type = "file" name = "files[]" data-url = "/photos/upload" multiple = "true" data-eventid = "#{@event.id}"
#progress
  .bar style = "width:0%"

app/views/layouts/application.html.slim
doctype html
html
  head
    title PicShare
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag params[:controller], media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags
    meta content="width=device-width, initial-scale=1.0" name = "viewport"

  body
    == render "/layouts/navbar"
    == yield
    == javascript_include_tag "application", "data-turbolinks-track" => true
    == javascript_include_tag params[:controller], "data-turbolinks-track" => true

app/views/photos/edit.html.haml
%h1 Editing photo

= render 'form'

= link_to 'Show', @photo
|
= link_to 'Back', photos_path

app/views/photos/edit.html.slim
h1 Editing photo

== render 'form'

= link_to 'Show', @photo
|
= link_to 'Back', photos_path

app/views/photos/index.html.slim
.container
  h1 Listing photos

  table
    thead
      tr
        th Thumbnail
        th Event
        th Caption
        th MD5
        th Adult content
        th
        th
        th

    tbody
      - @photos.each do |photo|
        tr
          td #{ image_tag photo.media_url, width: 64, height: 64 }
          td #{ photo.event.name }
          td #{ photo.caption }
          td #{ photo.md5 }
          td #{ photo.adult_content }
          td #{ link_to 'Show', photo }
          td #{ link_to 'Edit', edit_photo_path(photo) }
          td #{ link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } }

  b
    = link_to 'New Photo', new_photo_path

app/views/photos/new.html.slim
.container
  h1 Upload photos to #{@event.name}
  == render 'form'

app/views/photos/show.html.slim
.container

  p#notice #{ notice }

  p
    strong Md5:
    = @photo.md5

  p
    strong Caption:
    = @photo.caption

  p
    strong Adult content:
    = @photo.adult_content

  p
    strong Media URL:
    = @photo.media_url

  = link_to 'Edit', edit_photo_path(@photo)
  |
  = link_to 'Back', photos_path

app/views/welcome/index.html.slim
.container
  .jumbotron
    h1 Welcome to PicShare
    p PicShare is a place to share your event photos with friends, family, and the world!
    p There should be more text here. But there isn't.
    .btn-group
      a.btn.btn-lg.btn-primary.dropdown-toggle data-toggle='dropdown'
        | Find a recent event
          &nbsp
        span.caret
      ul.dropdown-menu
        - @events.each do |event|
          li #{ link_to event.name, {controller: 'events', action: 'show', id: event.id} }
    | &nbsp;&nbsp; or &nbsp;&nbsp;
    =link_to "Create a new event", {controller: "events", action: "new"}, class: 'btn btn-lg btn-primary'